export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

// whiteBoard:
export const DESELECT_NODE = 'DESELECT_NODE';
export const DESELECT_NODES = 'DESELECT_NODES';
export const SELECT_NODE = 'SELECT_NODE';
export const ADD_NODE = 'ADD_NODE';
export const UPDATE_SHAPE_PROPS = 'UPDATE_SHAPE_PROPS';
export const CHANGE_MODE = 'CHANGE_MODE';
export const REMOVE_SELECTED_NODES = 'REMOVE_SELECTED_NODES';
export const REMOVE_NODE = 'REMOVE_NODE';
export const INIT_WHITEBOARD = 'INIT_WHITEBOARD';
